name: Testing CMake FindPython

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run test
        shell: bash
        run: |
          python -m venv venv
          source venv/bin/activate

          echo "which python"
          which python

          cmake .
